title: Tim Kuiper
description: desc
baseurl: "baseurl"
url: https://tim-kuiper.github.io

theme: cvless

# site settings
taglong: DevOps Engineer
tagshort: Jekyll theme

# author settings
author:
  name: Tim Kuiper
  email: tim-kuiper.prism161@8shield.net
photo: assets/files/k8s.png
address: Wijhe

# social media links
social:
  github: tim-kuiper
  linkedin: https://www.linkedin.com/in/tim-kuiper-b690b9193/
  #stackoverflow: 0000000/username
  #x: username

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
