title: Tim Kuiper
description: desc
baseurl: "baseurl"
url: https://tim-kuiper.github.io

theme: cvless

# site settings
taglong: DevOps Engineer
tagshort: Jekyll theme

# author settings
author:
  name: Tim Kuiper
  email: tim.kuiper@protonmail.com
photo: assets/files/photo.jpg
address: Wijhe
# phone: +1 234 567 890

# social media links
social:
  #facebook: username
  github: tim-kuiper
  #instagram: username
  linkedin: test12345
  #stackoverflow: 0000000/username
  #x: username

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
