title: Tim Kuiper
description: desc
baseurl: "baseurl"
url: https://piazzai.github.io/cvless

theme: cvless

# site settings
taglong: DevOps Engineer
tagshort: Jekyll theme

# author settings
author:
  name: Tim Kuiper
  email: test@test.com
photo: assets/files/photo.jpg
address: Foobar Hall 1.23
phone: +1 234 567 890

# social media links
social:
  #facebook: username
  github: tim-kuiper
  #instagram: username
  linkedin: username
  #stackoverflow: 0000000/username
  #x: username

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
